### ISSUE TITLE
Add support for Concurrency/Threading

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#11]
I'm seeing some errors(false responses) while making much requests ( without all the direct connection code :p )

 tracked it to this:
if jsondata['rid'] != self.__request_id:

How does this happen ?
is this because multiple requests at same time and it answers for a previous one ?

seems the request_id is always higher then the jsondata rid for example
jsondata rid =	1504376192
request_id = 	1504376197

**Comment by mmarquezs** [comment]
> is this because multiple requests at same time and it answers for a previous one ?
If you are actually doing them at the same time. I mean you are using concurrency, threading,etc.., yes that's probably the reason. Right now you have to do a request, wait for the answer and then do the next but you can't do a request inbetween, at least not using the same instance of myjdapi.
Multiple instances of myjdapi might allow that unless I'm missing something. 
It can be fixed but probably not a simple solution (or thats what I think now). I could make a blocking system so it blocks the other requests until one finishes, it's not a good solution but it would be quick and easy until something better is done. 
But I have no clue if you're doing really doing concurrency. If you're not using concurrency it might be a bug.

**Comment by neox387** [comment]
Yea using gevent doing multiple greenlets per Download task using the same myjd instance. But sort of fixt it by only allowing 1 connection, got some more things I noticed will report when I have time

**Comment by mmarquezs** [comment]
Ok Thanks!
