### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#15]
Could you add a logger something like:

````
import logging
logging.basicConfig()
logger = logging.getLogger('myjdapi')
````
Cause I don't see the exceptions when using myjdapi as an import module, guess it can be done somehow but idk :)  

creating a logger.error or debug with the error message and returning False might be more useful then aborting in a raise ?

**Comment by mmarquezs** [comment]
It must be the way you run it. Because if you try it manually or doing a simple script you will get the exceptions.
A simple one:
```python
import myjdapi
j=myjdapi.Myjdapi()
j.disconnect()
```

This should get you an exception: 
> MYJDException: No connection established

**Comment by neox387** [comment]
ye right I see, was running it under a simple try / except without catching the error :/

doing it like this:
````
try:
    ...
except BaseException as e:
    logger.error('myjdapi : ' + e.message)
````
I get the error in my logger or have to make another logger with the name myjdapi :) , my bad :d
