### ISSUE TITLE
Change api endpoint to HTTPS

### ISSUE THREAD

**Issue by skinner12** [mmarquezs/My.Jdownloader-API-Python-Library#17]
Hello,

I'm using your version from PIP install and I saw it use old _HTTP_ protocol. If it's possible change to _HTTPS_ as it's written on official documentation.

Thanks

**Comment by mmarquezs** [comment]
I already change it on the develop branch , you can use it while you wait the master branch/pip to be updated. I want to test a little more the develop branch before merging it to master.
