### ISSUE TITLE
Invalid request not decrypted

### ISSUE THREAD

**Issue by spacemanspiff2007** [mmarquezs/My.Jdownloader-API-Python-Library#22]
When response != 200 the response does not get encrypted and the json-loading fails.

Line 837
`error_msg=json.loads(encrypted_response.text)`
should be
`error_msg=json.loads(self.__decrypt(self.__device_encryption_token,encrypted_response.text))`

**Comment by mmarquezs** [comment]
I can't check it right now. But I remember that there was a fix for that in  the develop branch. Maybe I didn't merge it on master/pip.
