### ISSUE TITLE
Update pypi package 

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#27]
Would be great if you could upload a new version to pypi from dev branch =D

**Comment by mmarquezs** [comment]
Yeah... I'm working on that...

**Comment by neox387** [comment]
Mkay thanks

**Comment by mmarquezs** [comment]
For now I added the new version as a dev version. So to install it it requires "--pre"

> pip3 install --pre myjdapi
