### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#3]
Another question, 

Atm when my app starts it does a connect. 

Everytime there is a Download I try to reconnect 

Is that right? I do this in case my connection isn't valid anymore, because there could be a day between the initial connect and adding links again.

**Comment by neox387** [comment]
allso the restrictions on packagename ? i'm doing str(re.sub('[^0-9a-zA-Z]+', ' ', greenlet.task.name).lower())

to strip all . / etc & doing everything in lowercase seems to be to only way not to get errors on packagename ..

but guess i'll better asks these questions to the support team

**Comment by mmarquezs** [comment]
yeah all that you better ask them. The first one well.. probably it's not the best but to be honest unless youre doing it in a short period of time I don't think it would be a problem but better ask to be sure. 
Probably I will have to improve the exceptions of the api, ideally in the future it will raise an exception if trying to do a request to the api  and it lost the connection, so you do something like reconnect,etc... Maybe even a setting you can turn on so it auto reconnects without an exception. 

An the second I don't know JDownloader itself it supports a lot of strange symbols but... I don't know if that cuases any problem with the api better ask them.
