### ISSUE TITLE
Basic Downloads.cleanup() call results Internal server error

### ISSUE THREAD

**Issue by ejamal** [mmarquezs/My.Jdownloader-API-Python-Library#30]
I am using your mydownloader api to send links for downloads just fine. However, recently, the following function

```
jd = Myjdapi()
jd.connect('hidden', 'hidden')
jd.update_devices()
device = jd.get_device(r'hidden') 
device.downloads.cleanup(action='DELETE_FINISHED',  mode='REMOVE_LINKS_ONLY', selection_type='ALL')
```
results in 
```
MYJDException: 
	SOURCE: DEVICE
	TYPE: INTERNAL_SERVER_ERROR
```
I tried to debug it to no avail. It would be great if you had a quick a look at it, it probably would not take you long to figure it out. I spent almost two days to figure out what is wrong and I can't. The [list of parameters](https://my.jdownloader.org/developers/#tag_131) expected by the API did not change.

Thanks in advance,

**Comment by ejamal** [comment]
I do not mind debugging it myself if you were to give me a couple of pointers. The function was working fine until recently, and the jdownloader API did not change. I believe the issue might be a change in behavior in one of the used modules.

**Comment by ejamal** [comment]
I take that back, something else fundamental is going wrong it's not just the cleanup. device.downloads.query_packages also fails with the same error.

**Comment by ejamal** [comment]
I pulled the the most recent version and it works, my bad.

**Comment by mmarquezs** [comment]
oh... I wanted to check it out today cause I had been a little busy. Well... I guess is not needed any more. 
Just one question @ejamal when you say you pulled the most the recent version. Did you did it from here or from pypi? Maybe pypi is out of date or something.

**Comment by ejamal** [comment]
If I remember correctly, the version that I have been using was from pypi and I did that a long time ago, more than a year or two. I just copied the contents of the version on the github and it worked.
