### ISSUE TITLE
Hi, is this still working with JD? Trying to find out if it is this or JD. no links added.

### ISSUE THREAD

**Issue by mmarquezs** [mmarquezs/My.Jdownloader-API-Python-Library#38]
Hi, is this still working with JD? Trying to find out if it is this or JD. no links added.

gracias

_Originally posted by @Mizio66 in https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/issues/18#issuecomment-817109704_

**Comment by mmarquezs** [comment]
I can help you here if you need help.

**Comment by heinrich-foto** [comment]
Everything works really good. It’s easy to use, and powerful. Thanks for the myDownloader API !!
