### ISSUE TITLE
How to Rename Package ?

### ISSUE THREAD

**Issue by Topspap** [mmarquezs/My.Jdownloader-API-Python-Library#47]
Hi 

Adding and renaming links is working fine...
but for `jd.linkgrabber.rename_package()`
"No idea what parameters i have to pass and/or i don't know what it does. If i find out i will implement it :P "

It is used to name the package which is contain the links, same as Folder of the files.

Any possibility to implement/fix it ?

Also, specifying destination Folder when adding link doesn't work or i didn't know how to use it !!
Here is how i used it when adding links:
`jd.linkgrabber.add_links("autostart": False,
                                        "links": "https://www.youtube.com/watch?v=xxxxxxxx&ab_channel=xxxxxxxx",
                                        "packageName": "Cooking",
                                        "destinationFolder": "D:\\Downloads\\CookingFolder")`

Thank you...

**Comment by mmarquezs** [comment]
Yeah I will try to look into implement it. The thing was that I didn't need it at the time or the documentation of myjdownloder wasn't very clear in some cases and had issues to make it work.


That said, about the second issue you mention check this issue, you aren't the first one to complain about it. I will have to put a warning or something in there. 
Is the design of how JDownloder deals with added links:

https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/issues/36

**Comment by mmarquezs** [comment]
Added jd.linkgrabber.rename_package() in the latest version.
https://pypi.org/project/myjdapi/1.1.2/
