### ISSUE TITLE
Compatibility with the depprecated API

### ISSUE THREAD

**Issue by slarrain** [mmarquezs/My.Jdownloader-API-Python-Library#50]
Hi,

Is this package compatible with the deprecated API? I have JDownloader running in a NAS on my LAN, so I can use the Deprecated API to connect directly without going through encription nor an external server.  I've been trying to user the `linkgrabberv2/addLinks` endpoint with `requests` but I have been unsuccessful. I was thinking that maybe this package could work, but by looking at the code it doesn't seem so.

This is what I have been trying to do:

```python
payload = {
'assignJobID': True,
 'autoExtract': False,
 'autostart': True,
 'dataURLs': [],
 'deepDecrypt': True,
 'destinationFolder': '',
 'downloadPassword': '',
 'extractPassword': '',
 'links': 'https://downmagaz.net/out.php?f=x&down=7751125400',
 'overwritePackagizerRules': True,
 'packageName': 'test',
 'priority': 'DEFAULT',
 'sourceUrl': ''
}
posturl = "http://NAS_IP:3128/linkgrabberv2/addLinks"

r = requests.post(
    posturl, 
    data=payload,
    headers={"Content-Type": "application/json; charset=utf-8"}
                 )
```

and I always get a `400` with 
```json
{
 "src"  : "DEVICE",
 "data" : "/linkgrabberv2/addLinks",
 "type" : "BAD_PARAMETERS"
}
```

I've tried multiple variations of `data=json.dumps(payload)` and so on. Nothing seems to work. Any ideas? 

Thank you in advance.

**Comment by mmarquezs** [comment]
No, it's all based on the the new api. 

That said, the api supports direct connections without going to my.jdownloader if it can connect to it and after the account has validated with my.jdownloader and so on. The support for this was added in this PR https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/pull/9 and mentioned in this issue https://github.com/mmarquezs/My.Jdownloader-API-Python-Library/issues/8#issuecomment-323521115 . So unless there is a bug or something is blocking the connection most of the requests will be send directly locally.

That said... I can understand not wanting to have an account at my.jdownloader and so on....  but unfortunately it doesn't support it. I am open to PR, but I don't use the library at all currently so except for small stuff or bug fixes I am not planning on doing big implementations.
