### ISSUE TITLE
no issue but request

### ISSUE THREAD

**Issue by sveni-lee** [mmarquezs/My.Jdownloader-API-Python-Library#6]
Hi Marc,

thanks for that great python Library. it works like a charm.
I've a little problem. I would like to use your library for an KODI addon. But you use pycrypto.
this will not work on KODU, unfortunatelly. so I tried to use [cryptopy](https://github.com/kodinerds/repo/tree/master/script.module.cryptopy)... so i changed line 674 as follow:
`decryptor = aes_cbc.AES_CBC(key=key, keySize=16)`

but I get the following error:
`    jd.connect("xxx","yyy")
  File "D:\lib\myjdapi\myjdapi.py", line 714, in connect
    response = self.request_api("/my/connect", "GET",[("email", email), ("appkey", self.__app_key)])
  File "D:\lib\myjdapi\myjdapi.py", line 854, in request_api
    response = self.__decrypt(self.__login_secret, encrypted_response.text)
  File "D:\lib\myjdapi\myjdapi.py", line 678, in __decrypt
    decrypted_data = UNPAD(decryptor.decrypt(base64.b64decode(data)))
  File "D:\lib\myjdapi\myjdapi.py", line 32, in UNPAD
    return s[0:-ord(s[-1])]
IndexError: string index out of range`

maybe you have a idea...

**Comment by mmarquezs** [comment]
One main problem with that library (not related with the error you're getting) is that either it doesn't support it or I don't see how I can pass it an inital vector (IV) which is needed. 

I suggest that you look into making work pycrypto. I know it uses C and that causes issues on kodi but I think it can be done. 
As alternative I have found this other pure python implementation that might work for this and you can check out:
https://github.com/ricmoo/pyaes
