### ISSUE TITLE
https

### ISSUE THREAD

**Issue by neox387** [mmarquezs/My.Jdownloader-API-Python-Library#8]
Hey,

Any reason why you using http instead of https://api.jdownloader.org ?

just tested and seems to work fine with https.

**Comment by mmarquezs** [comment]
At the beginning of the api there wasn't https, but I honestly can't remember if when I started there was already https. Maybe it was already there and I just didn't think about it. 

To be honest the connection to the api it's already secure so using https might be a little overkill, but I could switch to it and maybe add an option to use http if needed.

**Comment by neox387** [comment]
Ok,

just saw it on [https://my.jdownloader.org/developers/index.html ](https://my.jdownloader.org/developers/index.html ) that it only states https.

Also; You don't have plans to support RemoteAPI:Deprecated Api I suppose ? :)
saw this on the above link:
Pro Tip: It's possible to access the JDownloader API directly (Bypass our server) by enabling the so called 'Deprecated API' in the Advanced Options.

but this would mean going to localhost:3128 and not https://api.jdownloader.org

**Comment by mmarquezs** [comment]
> just saw it on https://my.jdownloader.org/developers/index.html that it only states https.

Honestly the last time I used documentation there wasn't a documentation so fancy as that one. I had this: https://docs.google.com/document/d/1IGeAwg8bQyaCTeTl_WyjLyBPh4NBOayO0_MAmvP5Mu4/edit

> Also; You don't have plans to support RemoteAPI:Deprecated Api I suppose ? :)
saw this on the above link:
> Pro Tip: It's possible to access the JDownloader API directly (Bypass our server) by enabling the so called 'Deprecated API' in the Advanced Options.
> but this would mean going to localhost:3128 and not https://api.jdownloader.org

In the beginning I started creating this api to use it in a project of mine. That project basically needed to download several files from differents host and basically I wanted to use JDownloader to queue,track and download the files. Both the program and JDownloader were going to be in the same Machine, so I didn't like too much the need to connect to my.jdownloader servers to do something but it was easy to make it work this way.  The plan was to implement the local way in the future. 

At the end I didn't make that project so I didn't look into it more but I'm still interested in making it work this way if I can.  Once said this, there is a middle ground between the Deprecated api you suggest  and My.JDownloader. It requeries to connect to My.JDownloader and have and account but once connected you can connect locally, I probably would implement this first but I have to find how does that work. I know I can ask a Device for  "DirectConnectionInfo" but not sure yet how I send things to it. 

The deprecated API is better if you don't want to connect to them at all, which is nice for privacy or other reasons and I like it. The problems are:

- There isn't a lot of documentation about it.
- It might be a very different than this api and might require a new library.
- It is a deprecated api so at any moment they might decide to remove it all together from the app.

**Comment by neox387** [comment]
Yes I see the direct connect seems to be the answer, working from the web ui: Direct connection to https://127.0.0.1:8905.

browsing on the Jdownloader 2 forum found this topic check the posts from Jiaz: [JDownloader in my Application](https://board.jdownloader.org/showthread.php?t=66358&page=2)

post 27:
````
You call the command /device/getDirectConnectionInfos on the device(your JDownloader)
the answer contains a list of IP/PORT 
Then you can use
IP:PORT instead of api.jdownloader.org and use the command /device/ping if the connection works
if yes, use the IP:PORT for all further device requests
if no, try next IP:PORT and check again

you simply exchange api.jdownloader.org with the IP:PORT that works, nothing more, nothing less
````

post 33:
````
you simply use
$api_url = "http://api.jdownloader.org"
for all commands that are server side (eg account stuff)
and
$api_url = "http://IP:PORT"; 
for all commands that are jdownloader side
````

**Comment by neox387** [comment]
after much testing I finally got it working =D, Ill make pull request

**Comment by mmarquezs** [comment]
Nice I was going to work on it this weekend since I don't have a lot of time this days. I'll check it out.
